### ISSUE TITLE
Example code is not working

### ISSUE THREAD

**Issue by abhishektiwari** [RemieJanssen/PhyloX#42] opened 2024-03-09 22:35 UTC
**Describe the bug**
Running example code [here](https://phylox.readthedocs.io/en/latest/index.html)

```py
from phylox.generators.randomTC import generate_network_random_tree_child_sequence
from phylox.generators.mcmc import sample_mcmc_networks
from phylox.classes import is_orchard
from phylox.rearrangement.move import MoveType

# Generate an arbitrary orchard network with 10 leaves and 5 reticulations
start_network = generate_network_random_tree_child_sequence(10, 5)
# Generate 1000 orchard networks with 10 leaves and 5 reticulations
sampled_networks = sample_mcmc_networks(
   start_network,
   {MoveType.TAIL: 0.5, MoveType.HEAD: 0.5},
   number_of_samples=100,
   burn_in=100,
   restriction_map=is_orchard,
   seed=1234,
   add_root_if_necessary=True,
)
# Write the sampled networks to a file
with open("sampled_networks.nwk", "w") as f:
   for network in sampled_networks:
      f.write(network.newick() + "\n")
```

**Error**
```
Traceback (most recent call last):
  File "/home/ubuntu/Home/joss/phylox/test.py", line 9, in <module>
    sampled_networks = sample_mcmc_networks(
  File "/home/ubuntu/.pyenv/versions/phylox/lib/python3.9/site-packages/networkx/utils/decorators.py", line 770, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 20", line 4, in argmap_sample_mcmc_networks_17
  File "/home/ubuntu/.pyenv/versions/phylox/lib/python3.9/site-packages/phylox/generators/mcmc/base.py", line 173, in sample_mcmc_networks
    if not (restriction_map is None or restriction_map(result_network)):
  File "/home/ubuntu/.pyenv/versions/phylox/lib/python3.9/site-packages/phylox/classes/dinetwork.py", line 90, in is_orchard
    leaves.remove(pair[0])
KeyError: 9
```

For [JOSS Review](https://github.com/openjournals/joss-reviews/issues/6427)

**Comment by bgyori** [comment] 2024-03-23 19:17
As a second reviewer, I can confirm that I ran into the same bug. @RemieJanssen are you planning to address this?

**Comment by RemieJanssen** [comment] 2024-03-24 10:44
I see, I get the same error. I am definitely fixing this!

**Comment by RemieJanssen** [comment] 2024-03-24 12:42
It seems to be a problem with deepcopying of networks in combination with caching of some network properties.

**Comment by RemieJanssen** [comment] 2024-03-24 13:00
WIP in https://github.com/RemieJanssen/PhyloX/pull/45

**Comment by RemieJanssen** [comment] 2024-03-26 18:43
@abhishektiwari @bgyori I fixed the example and merged it into the main branch already. Feel free to test it again. If you would rather do that with a new version via pip, I can make a new release. Though, I'd prefer to bundle it with some more fixes, if you find any more bugs.

I'll close this issue once any of you can confirm the example works.

**Comment by abhishektiwari** [comment] 2024-03-27 01:31
Thank you. I will look into this tomorrow and revert back to you.

**Comment by abhishektiwari** [comment] 2024-04-06 13:56
Confirming example works now when using source install. I assume next release should have these fixes.

**Closed** 2024-04-06 13:57 UTC
